### ISSUE TITLE
How to understand the results of EmerGNN

### ISSUE THREAD

**Issue by lesyngenta** [LARS-research/EmerGNN#3]
Dear author,

I tried the EmerGNN codes using the examples in TWOSIDES and completed the evaluate.py smoothly. However, the only out put results is the model evaluation results. How I could find the drug-drug interaction information defined by the best model?

Thanks,
Le

**Comment by yzhangee** [comment]
Sorry for the late reply. We are busy with several issues these days. 

Thank you for your interest in our paper and code. The scores can be obtained through the code `torch.sigmoid(self.model.enc_r(self.model.enc_ht(p_h, p_t, KG)))` given the source drugs p_h, p_t and the biomedical network KG. And you can pick up the interaction with the highest score according to the returned values.

**Comment by lesyngenta** [comment]
Thanks a lot for the response!
